### ISSUE TITLE
Make documentation great again

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#265]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | no
| New feature?    | no
| Question?       | no
| Documentation?  | yes
| Related tickets | #260, #261, #259, #275

- [x] Add information about which part of the code is being checked by GrumPHP. (#260)
- [x] Add information about how to skip test and why you should not do that. (#261)
- [x] Add information about why we do not support automated code fixes (#259)
- [x] Add a line of required composer packages in the task documentation. This way you can just browse to the task config and get full feedback on how to implement it. (Yes, I tend to forget to require the package :) )
- [x] Add information about current windows limitations (#275)
- [x] Make sure the badges in the readme display the state of the master branch. They should not change when a PR errors.

**Comment by tombevers** [comment]
The badges seem correct in the README file

**Comment by veewee** [comment]
Thanks @tombevers  and @bvanderstee  for your work on the documentation!
