### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#957]
| Q               | A
| --------------- | ---
| Version         | `vendor/bin/grumphp -V`
| Bug?            | no
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets |

We added PHP 8.1 compatibility in #956.
However, not all downstream packages are fully compatible yet.
Therefore, you might still see some deprecation warnings.
The tool itself should be working though!

Awaiting deps:

- [x] opis/closure: https://github.com/opis/closure/pull/105
- [x] opis/closure:  https://github.com/opis/closure/issues/59
- [x] laravel/closure if amphp/parallel-functions wants to use that: https://github.com/amphp/parallel-functions/pull/29

Awaiting dev deps
- [x] phpspec: https://github.com/phpspec/phpspec/pull/1397

Awaiting shim deps (patched locally)

- [x] humbug/box & scoper: https://github.com/box-project/box/issues/562
- [x] scoper issue with serializable closure: https://github.com/humbug/php-scoper/issues/642
- [x] scoper issue with union return types https://github.com/humbug/php-scoper/issues/643
- [x] New shim build setup : https://github.com/phpro/grumphp-shim/pull/17

Broken Tests

- [ ] ~Fix skipped E2E tests~ - currently won't do. They seem buggy edge cases anyways. If there is any need for them to still work, time can be invested

**Comment by Carpenter0100** [comment]
Hi, 
thank you for this.
Is it possible to update "psr/container" too?

**Comment by dvdknaap** [comment]
@veewee please also add psr/container there are packages that can't be upgrade because grumphp is still using v1

**Comment by veewee** [comment]
Idd surely accept a PR for that..

**Comment by dvdknaap** [comment]
> Idd surely accept a PR for that.. care to give it a try?

Please check #968

**Comment by ctrl-f5** [comment]
Are you guys willing to switch to the https://github.com/laravel/serializable-closure fork?

Since I agree with the remarks on opis/closure that depending on FFI is not a very good idea.

**Comment by veewee** [comment]
I am willing to switch to whatever works best.
However, `amphp/parallel-functions` is still using `opis/closure`, so I don't know if we can rule it out completely:

https://github.com/amphp/parallel-functions/blob/master/composer.json#L29

Lets keep an eye on this issue as well:
https://github.com/amphp/parallel-functions/pull/29

**Comment by tm1000** [comment]
@veewee there are some remarks in the `opis/closure` thread that FFI is also very slow

**Comment by veewee** [comment]
@tm1000 it's not that simple ... laravel/closure is not marked as a replacement for opis/closure. See composer.json
So even if we switched to laravel/closure, it 'll still mean that amp/parallel-functions would have to use that same package internally. Since the namespace changed, it cannot be marked as a replacement anyways.

**Comment by leonexcc** [comment]
amphp/parallel-functions released a version 1.1.0 with laravel/closure. This now breaks grumphp on PHP 8.1 with:

<code>
Uncaught Amp\Serialization\SerializationException in worker with message "The given data could not be serialized: Laravel\SerializableClosure\Support\ReflectionClosure::__construct(): Argument #1 ($closure) must be of type Closure, Opis\Closure\SerializableClosure given, called in .../vendor/laravel/serializable-closure/src/Serializers/Native.php on line 300" and code "0"; use Amp\Parallel\Worker\TaskFailureException::getOriginalTrace() for the stack trace in the worker
</code>

**Comment by veewee** [comment]
Nice! Thanks for mentoning @leonexcc. 
I'm a bit short on time ATM, Care to unbreak it?

**Comment by janvernieuwe** [comment]
Also broken on php7.4 since parallel function 1.1.0, pinning does fix it there too

**Comment by veewee** [comment]
Locked it to 1.0 for 1.7.1.
We can launch the compatibility with the new larevel version in grumphp v1.8 - but that will fix composer update issues for now

**Comment by mougrim** [comment]
Hi! Could somebody do same fix as https://github.com/phpro/grumphp/pull/981 and https://github.com/phpro/grumphp/pull/982 for grumphp v1.5.0?

Grumphp 1.7.1 requires php8.0, bug  php7.4 is still supported (have security fixes).

Or say, how to do it correctly (I see here only master branch).

**Comment by veewee** [comment]
@mougrim : I also patched this locked version to v1.5.1

**Comment by veewee** [comment]
Released the fixes for the serializable closure
https://github.com/phpro/grumphp/releases/tag/v1.8.0

**Comment by danepowell** [comment]
I'm still seeing this using v1.5.1 on PHP 7.4: 

> PHP Deprecated:  GrumPHP\Collection\FilesCollection implements the Serializable interface, which is deprecated.

I presume this is fixed in v1.8.1, but can we get this backported to a version compatible with PHP 7.4 as well?

**Comment by veewee** [comment]
@danepowell I'm a bit confused here. That interface is deprecated in php 8.1. Since you are on 7.4, you shouldnt be getting that deprecation warning?

**Comment by danepowell** [comment]
No problem, I should have explained. We use grumphp in an application that must run on any supported PHP version (7.4-8.1) for end users. Thus we need to use grumphp v1.5.1, as it's the latest to support PHP 7.4. But if a user on PHP 8.1 runs our app, they get the deprecation errors.

Specifically, we use [Composer's platform config](https://getcomposer.org/doc/06-config.md#platform) to mandate support of PHP 7.4 in [our composer.json](https://github.com/acquia/cli/blob/db1ba41490dca8b3254f5346e9c225ae8f0b4574/composer.json#L78).

**Comment by danepowell** [comment]
Is there any reason that PHP 7.4 compatibility was explicitly dropped in https://github.com/phpro/grumphp/pull/956? As far as I can tell, the code in master should be cross-compatible with PHP 7.4 and PHP 8 except for the explicit Composer php dependency.

Restoring PHP 7.4 compatibility in HEAD seems much more maintainable than backporting PHP 8 to v1.5.1, which essentially becomes a forked and non-LTS branch.

**Comment by veewee** [comment]
We usually support latest 2 versions. That makes the dependency tree easier to maintain. (And less time consuming)
That means lowest supported version is in security update only mode, which is considered not really that supported in my book.

For older php versions you can then use older grumphp versions without any issue.

But indeed , if you have to support all active php versions in projects and want to use grumphp, that's an issue.
